name: Latest Medium Articles Workflow

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write # Required to update the README

jobs:
  update-readme-with-medium-articles:
    name: Update README with latest Medium articles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@ryan.adams1277"
          # Optional: you can set output_file if you want a custom file instead of README
          # output_file: "BLOG_POSTS.md"
